version: '3'
services:
  api:
    container_name: api
    image: rcbj/api
    environment:
     - HOST=0.0.0.0
     - PORT=4000
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  client:
    container_name: client
    image: rcbj/client
    environment:
     - BASE_URL=http://localhost:3000
     - API_URL=http://localhost:4000
     - HOST=0.0.0.0
     - PORT=3000
    build:
      context: client
      dockerfile: Dockerfile 
      args:
        CONFIG_FILE: ${CONFIG_FILE}
    ports:
      - "3000:3000"
