name: Docker Image CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: debug1
         run: echo "BRANCH_NAME=${GITHUB_REF}"
       - uses: actions/checkout@v1
         with:
           ref: ${GITHUB_REF}
