name: Docker Image CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
#         with:
#           ref: ${{ github.ref_name }}
       - name: Install docker-compose
         uses: KengoTODA/actions-setup-docker-compose@v1
         with:
           version: '2.14.2'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
       - name: build
         run: CONFIG_FILE=./env/local.js docker-compose build
