name: Docker Image CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
       - name: Install docker-compose
         uses: KengoTODA/actions-setup-docker-compose@v1
         with:
           version: '2.14.2'
       - name: build
         run: CONFIG_FILE=./env/local.js docker-compose -f docker-compose.yml build
